language: python            # this works for Linux but is an error on macOS or Windows

git:
  depth: 1

branches:
  only:
  - master
  - setuptools_cmake

env:
  global:
  - LIBSBML_SRC_DIR=/home/travis/build/sbmlteam/python-libsbml/libsbml_trunk

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH


before_install:
  - (svn co -q https://svn.code.sf.net/p/sbml/code/trunk/libsbml libsbml_trunk && echo $PWD)
  - pip install -U pip setuptools wheel tox
  
script:
  - python3 setup.py build || python setup.py build
